name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variables from GitHub Secrets
        run: echo "VERYSECRETOPENWEATHERMAPAPIKEY=${{ secrets.VERYSECRETOPENWEATHERMAPAPIKEY }}" >> $GITHUB_ENV

      - name: Deploy to GitHub Pagesand i
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          clean: true
